### PR TITLE
Arcane Spellcasting Pt.2.5 (Spellbooks/Craft/Learn)

### PR DESCRIPTION
**Pull request by tioluko**
### **Bug fixes:**

- Smokescreen now _smokes_ properly (the stuff stripped from atmos made it stop working the way it used to be, I had to manually remake said effect)
- Fixed some spells that were not properly giving Arcane skill experience on cast
- Wizard's Apprendice was broke because of the **" ' "** in its name (yep, not a joke). It is fixed anyway (Please, let me know if y'all do not want it back in the game so I can disable it) 

### **Changes:**

- **Magic Tomes** 
You can now craft Magic Tomes (Spellbooks) that you or another character can use to learn the spell inscribed on it. _( I used [this pull](https://github.com/Blackstone-SS13/BLACKSTONE/pull/748) from [NGGJamie](https://github.com/NGGJamie) as a base and a adapted it to work here)_
Crafting a Tome requires to use Magic Feather (Feather + Dust) into a 5-page manuscript, if successful (The more Int and Arcane skill, the better) it will create a new Tome with a random spell inscribed on it, however, _you'd be for a nasty surprise if it fails..._
They are easily converted into dungeon/random drops if you wish to, and are all single use items becoming useless after someone with enough arcane and (obviously) reading skill  "absorbs" its contents. (Also, the max amount of spells any any arcane caster is tied to his own arcane skill)

buk

- **New arcane spells:**   
Caxxpturar
**Conjure Webs**	-Creates a small cluster of spider webs in the target location.
**Conjure Chains**   -Shackles a prone target with conjured chains (He needs to be lying down for it to work)
**Decay bolt**	        -Dark magic bolt that deals light damage and makes the target sick.
**Mist**                   -Fills the screen surrounding the caster with a temporary mist.
**Arcane Light**       -Temporary light source.
**Magic Wall**          -Weak temporary 3x1 magic wall that the caster can freely cross (break easily with a few blunt hits).
**Fire Wall**              -Ignite flames in a 3x1 area of your choosing.
**Featherweight**     -Becomes temporarily resistant to fall damage and capable of zJumping like a Jester.
**Ensnaring Roots**  -Grow roots in a 3x3 area that temporarily holds any target into it. (Dendor Approves)
**Unlock**                  -Try to magically unlock a door or closet (can fail and definitely cant be used on the bank)
**Repulse**                -Summon an arcane force that forcefully repels any object or person away from you.

- **Casting Animation** 
A little animation on the caster after a spell is used.
Some spells have a bit of confusion/shittery potential and something to signal when/who is casting something is really necessary.

- **Mage's Apprentice?** 
A little shit for the Court Magician to take care of, frail as any other teenager but with a little arcane knowledge and few spells (don't worry, then don't start with any _murder magic_ ... I mean, at least not the ones created exclusively for _murder_ )
**(Still disabled by default, but he is functional in case you want include him)**

### **TODO/IDEAS:**

-Single use spell-scrolls that can be craftable in a similar fashion (Inscribing a spell you know in it, making it a single use spell that anyone with decent reading skill can use)
-Make so you it is possible cast the spell in the Tome straight from it without actually consuming it to permanently learn the same spell
-Reduce the overall jankiness of the entire process (It works, but it still not in a _ideal_ state)
-Make some fancy _work in progress_ spells I have in the oven to stop being a massive headache and actually start working properly (Namely: polymorph, unlock, magic bag and others)

## Why It's Good For The Game
Make magic fun, **ALL PRAISE NOC !**

Jokes aside, it is legit something for Court Mages/Apprendices to do instead of just hanging in the keep waiting for something to happen...  and mage adventures can also seek them out for buying those.

And more importantly, [many of those spells can be given to divine caster tables as well](https://docs.google.com/document/d/1_8Q3aNgoXhcqenR1Ez8mYPx3EIVJmRS82KSgTX2a4Ag/edit), I only need the green-light to start doing so, and start giving divine casters the same attention.

### CODE REVIEW

**Comment by tioluko** [comment]
I think this is also a good excuse for bringing back the Wizard's apprendice job (They work in theory, they just need to be enabled back in the game)

**Comment by kaylexis** [comment]
> I think this is also a good excuse for bringing back the Wizard's apprendice job (They work in theory, they just need to be enabled back in the game)

i've attempted this actually, it's mysteriously broken and i can't find out why. from what I see in this PR you tried almost exactly what I did, I recommend testing if you intend on enabling it

**Comment by tioluko** [comment]
> i've attempted this actually, it's mysteriously broken and i can't find out why. from what I see in this PR you tried almost exactly what I did, I recommend testing if you intend on enabling it

**I shit you not..**. the reason for it to be "misteriously broken" was the " **'s** " before the "apprentice"

Yes.   I can't even...


In any case, It is enable back here in this pull (but let me know if y'all dont want it back in the game so I can turn it back off)

**Comment by tioluko** [comment]
Closed and Reopened because I needed to rework/add a lot of stuff. (Just to avoid the slight chance of it getting merged while I was working on these changes)

and re-disabled Mage Apprendice by default (but he is functional now in case you want to re-add him)

**Pull request closed without merging**
